version: '3.8'

services:
  sqlserver:
    image: my-third-image
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "sqlcmd", "-U", "SA", "-P", "password@12345#", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - sql_data:/var/opt/mssql
      

  webapi:
    image: my-first-image
    ports:
      - "50306:80"
    networks:
      - mynetwork
    depends_on:
      - sqlserver
    restart: on-failure

  angularapp:
    image: my-second-image
    ports:
      - "4201:4200"
    networks:
      - mynetwork
    depends_on:
      - webapi
    restart: on-failure

networks:
  mynetwork:
    driver: bridge

volumes:
  sql_data:

